### ISSUE TITLE
Getting Errors , help needed.

### ISSUE THREAD

**Issue by kratos-is-alive** [m4ll0k/SecretFinder#18]
while running this tool with "-e" for example : python3 SecretFinder.py -i https://www.domain.com -e

It is giving this error ,

Traceback (most recent call last):
  File "SecretFinder.py", line 433, in <module>
    matched = parser_file(file,mode)
  File "SecretFinder.py", line 180, in parser_file
    items = getContext(all_matches,content,regex[0])
  File "SecretFinder.py", line 156, in getContext
    context = re.findall('%s%s%s'%(rex,m,rex),content,re.IGNORECASE)

Also this tool was working amazingly few days before but as i update mp ubuntu to newer version and installed it again this tool is not working fine .

Please help.

**Comment by mrthankyou** [comment]
I'm also experiencing this error. However, in my case the code stalls and only when exiting do I receive an error:

```
ecretFinder.py -i /file_path.js
[ + ] URL: file:///file_path.js
^CTraceback (most recent call last):
  File "SecretFinder.py", line 434, in <module>
    matched = parser_file(file,mode)
  File "SecretFinder.py", line 181, in parser_file
    items = getContext(all_matches,content,regex[0])
  File "SecretFinder.py", line 157, in getContext
    context = re.findall('%s%s%s'%(rex,m,rex),content,re.IGNORECASE)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/re.py", line 223, in findall
    return _compile(pattern, flags).findall(string)
KeyboardInterrupt
```

**Comment by RAVIPRAJ** [comment]
i am also facing this error some time ago because of wrong command type like this and
secretfinder will work fine

python3 SecretFinder.py -i https://www.example.com/main.js -o cli -r 'apikey=my.api.key[a-zA-Z]+'
