### ISSUE TITLE
File Example?

### ISSUE THREAD

**Issue by random-robbie** [m4ll0k/SecretFinder#2]
Trying to use a bit list of urls but getting no joy.

```
root@bb1:~/SecretFinder# python3 SecretFinder.py -i file://urls.txt -o output
[ + ] URL: file://urls.txt
Traceback (most recent call last):
  File "SecretFinder.py", line 402, in <module>
    file = send_request(url)
  File "SecretFinder.py", line 320, in send_request
    return s.get(url).content.decode('utf-8','replace')
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/requests_file.py", line 34, in send
    raise ValueError("file: URLs with hostname components are not permitted")
ValueError: file: URLs with hostname components are not permitted
```

**Comment by m4ll0k** [comment]
@random-robbie  - this version of tool not accept the list of urls
