### ISSUE TITLE
 args.header.split('\\n') should be args.headers.split('\\n') in line 354

### ISSUE THREAD

**Issue by henrique-marcomini-movile** [m4ll0k/SecretFinder#20]
Hi, in the line 354 of SecretFinder.py  there is a call to args.header, but the correct according to the object is headers

so line 354 becomes args.headers.split('\\n')

**Comment by m4ll0k** [comment]
```py 
import argparse

a = argparse.ArgumentParser()
a.add_argument('-a','--aa',help="ok",default="")
b = a.parse_args()
print(b.aa.split('\\n'))
```

**Comment by henrique-marcomini-movile** [comment]
To clarify it, the error that I'm trying tackle here is this one

```
$git branch
* master


$python3 SecretFinder.py 
usage: SecretFinder.py [-h] [-e] -i INPUT [-o OUTPUT] [-r REGEX] [-b]
                       [-c COOKIE] [-g IGNORE] [-n ONLY] [-H HEADERS]
                       [-p PROXY]
SecretFinder.py: error: the following arguments are required: -i/--input


$python3 SecretFinder.py -H "test" -i "https://something"
[ + ] URL: https://something
Traceback (most recent call last):
  File "SecretFinder.py", line 428, in <module>
    file = send_request(url)
  File "SecretFinder.py", line 354, in send_request
    for i in args.header.split('\\n'):
AttributeError: 'Namespace' object has no attribute 'header'
```

There is mismatch due to 

```
parser.add_argument("-H","--headers",help="Set headers (\"Name:Value\\nName:Value\")",action="store",default="")
```
and then calling it like this on line 354
```
for i in args.header.split('\\n'):
```

**Comment by storenth** [comment]
@m4ll0k Looks like I get `AttributeError`, while using `-H` argument
```bash
export CUSTOMHEADER='X-HackerOne-Research:storenth'
xargs -I '{}' secretfinder -H $CUSTOMHEADER -i {} -o cli < ./js-list.txt
```
<img width="501" alt="header-issue" src="https://user-images.githubusercontent.com/18244131/146049236-9b5cc3fb-5e9f-4c03-b8f5-f9247814d88f.png">

Note: works fine without `-H`.
Do we need a separate issue?
