### ISSUE TITLE
error line 456

### ISSUE THREAD

**Issue by s4s0r1** [m4ll0k/SecretFinder#34]
Traceback (most recent call last):
  File "SecretFinder.py", line 456, in <module>
    body += '</a><div class="container">%s</div></div>'%(match.get('context')[0])

**Comment by Phoenix1112** [comment]
same problem

```
root@localhost:~/SecretFinder# python3 SecretFinder.py -i results.txt -o output.txt
[ + ] URL: file:///root/SecretFinder/results.txt
Traceback (most recent call last):
  File "SecretFinder.py", line 456, in <module>
    body += '</a><div class="container">%s</div></div>'%(match.get('context')[0])
IndexError: list index out of range
```

**Comment by m4ll0k** [comment]
Hi guys, i think is fixed!
