### ISSUE TITLE
error again

### ISSUE THREAD

**Issue by s4s0r1** [m4ll0k/SecretFinder#35]
Traceback (most recent call last):
  File "SecretFinder.py", line 434, in <module>
    matched = parser_file(file,mode)
  File "SecretFinder.py", line 181, in parser_file
    items = getContext(all_matches,content,regex[0])
  File "SecretFinder.py", line 157, in getContext
    context = re.findall('%s%s%s'%(rex,m,rex),content,re.IGNORECASE)
  File "/usr/lib/python3.8/re.py", line 241, in findall
    return _compile(pattern, flags).findall(string)
  File "/usr/lib/python3.8/re.py", line 304, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/usr/lib/python3.8/sre_compile.py", line 764, in compile
    p = sre_parse.parse(p, flags)
  File "/usr/lib/python3.8/sre_parse.py", line 962, in parse
    raise source.error("unbalanced parenthesis")
re.error: unbalanced parenthesis at position 13

**Comment by m4ll0k** [comment]
command?

**Comment by RAVIPRAJ** [comment]
hey @s4s0r1 
i am also facing this error some time ago because of wrong command type like this and
secretfinder will work fine

python3 SecretFinder.py -i https://www.example.com/main.js -o cli -r 'apikey=my.api.key[a-zA-Z]+'
