### ISSUE TITLE
Error when loading Burp version 2020.12

### ISSUE THREAD

**Issue by kelleybryant** [m4ll0k/SecretFinder#37]
Getting an error when loading in Burp:

`Traceback (most recent call last):
  File "C:\tools\SecretFinder-master\SecretFinder.py", line 10, in <module>
    sys.exit(0)
SystemExit: 0

	at org.python.core.PySystemState.exit(PySystemState.java:1505)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.python.core.PyReflectedFunction.__call__(PyReflectedFunction.java:188)
	at org.python.core.PyReflectedFunction.__call__(PyReflectedFunction.java:206)
	at org.python.core.PyObject.__call__(PyObject.java:497)
	at org.python.core.PyObject.__call__(PyObject.java:501)
	at org.python.core.PyMethod.__call__(PyMethod.java:141)
	at org.python.pycode._pyx4.f$0(C:/tools/SecretFinder-master/SecretFinder.py:463)
	at org.python.pycode._pyx4.call_function(C:/tools/SecretFinder-master/SecretFinder.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:171)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.Py.runCode(Py.java:1614)
	at org.python.core.__builtin__.execfile_flags(__builtin__.java:535)
	at org.python.util.PythonInterpreter.execfile(PythonInterpreter.java:286)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at burp.avb.<init>(Unknown Source)
	at burp.co7.a(Unknown Source)
	at burp.d_u.lambda$panelLoaded$0(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
`

**Comment by kelleybryant** [comment]
The above error is not happening anymore after I upgraded to python3 in Burp.  Getting a new error now:

java.lang.Exception: Failed to load Python interpreter from Jython JAR file
	at burp.avb.<init>(Unknown Source)
	at burp.co7.a(Unknown Source)
	at burp.d_u.lambda$panelLoaded$0(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)

**Comment by kelleybryant** [comment]
Looks to be an issue with Jython.  Is there a particular version that this plugin works with?  I'm using:  Jython is 2.7.2

**Comment by m4ll0k** [comment]
try using jython 2.7.1
