### ISSUE TITLE
Error on scanning

### ISSUE THREAD

**Issue by Arun-Josh** [m4ll0k/SecretFinder#43]
at org.python.core.PyBaseCode.call(PyBaseCode.java:306)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:197)
	at org.python.core.PyFunction.__call__(PyFunction.java:485)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:237)
	at org.python.core.PyMethod.__call__(PyMethod.java:228)
	at org.python.core.PyMethod.__call__(PyMethod.java:218)
	at org.python.core.PyMethod.__call__(PyMethod.java:213)
	at org.python.core.PyObject._jcallexc(PyObject.java:3565)
	at org.python.core.PyObject._jcall(PyObject.java:3598)
	at org.python.proxies.__main__$BurpExtender$7.doPassiveScan(Unknown Source)
	at burp.g5c.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Traceback (most recent call last):
  File "/home/user/Dragon/Bug_Hunter/SecretFinder-master/BurpSuite-SecretFinder/SecretFinder.py", line 113, in doPassiveScan
    BurpExtender.issuename%(' '.join([x.title() for x in reg[0].split('_')])), 
  File "/home/user/Dragon/Bug_Hunter/SecretFinder-master/BurpSuite-SecretFinder/SecretFinder.py", line 143, in findRegEx
    myre = re.compile(regex, re.VERBOSE)
  File "/home/user/Dragon/Bug_Hunter/BurpSuitePro-2.0.11-Beta/jars/jython-standalone-2.7.2.jar/Lib/re.py", line 190, in compile
  File "/home/user/Dragon/Bug_Hunter/BurpSuitePro-2.0.11-Beta/jars/jython-standalone-2.7.2.jar/Lib/re.py", line 242, in _compile
sre_constants.error: multiple repeat

	at org.python.core.PyException.doRaise(PyException.java:211)
	at org.python.core.Py.makeException(Py.java:1638)
	at org.python.core.Py.makeException(Py.java:1642)
	at re$py._compile$12(/home/user/Dragon/Bug_Hunter/BurpSuitePro-2.0.11-Beta/jars/jython-standalone-2.7.2.jar/Lib/re.py:246)
	at re$py.call_function(/home/user/Dragon/Bug_Hunter/BurpSuitePro-2.0.11-Beta/jars/jython-standalone-2.7.2.jar/Lib/re.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:173)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:306)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:141)
	at org.python.core.PyFunction.__call__(PyFunction.java:426)
	at re$py.compile$8(/home/user/Dragon/Bug_Hunter/BurpSuitePro-2.0.11-Beta/jars/jython-standalone-2.7.2.jar/Lib/re.py:190)
	at re$py.call_function(/home/user/Dragon/Bug_Hunter/BurpSuitePro-2.0.11-Beta/jars/jython-standalone-2.7.2.jar/Lib/re.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:173)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:150)
	at org.python.core.PyFunction.__call__(PyFunction.java:426)
	at org.python.pycode._pyx4.findRegEx$8(/home/user/Dragon/Bug_Hunter/SecretFinder-master/BurpSuite-SecretFinder/SecretFinder.py:167)
	at org.python.pycode._pyx4.call_function(/home/user/Dragon/Bug_Hunter/SecretFinder-master/BurpSuite-SecretFinder/SecretFinder.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:173)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:306)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:197)
	at org.python.core.PyFunction.__call__(PyFunction.java:485)
	at org.python.core.PyMethod.__call__(PyMethod.java:187)
	at org.python.pycode._pyx4.doPassiveScan$5(/home/user/Dragon/Bug_Hunter/SecretFinder-master/BurpSuite-SecretFinder/SecretFinder.py:122)
	at org.python.pycode._pyx4.call_function(/home/user/Dragon/Bug_Hunter/SecretFinder-master/BurpSuite-SecretFinder/SecretFinder.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:173)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:306)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:197)
	at org.python.core.PyFunction.__call__(PyFunction.java:485)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:237)
	at org.python.core.PyMethod.__call__(PyMethod.java:228)
	at org.python.core.PyMethod.__call__(PyMethod.java:218)
	at org.python.core.PyMethod.__call__(PyMethod.java:213)
	at org.python.core.PyObject._jcallexc(PyObject.java:3565)
	at org.python.core.PyObject._jcall(PyObject.java:3598)
	at org.python.proxies.__main__$BurpExtender$7.doPassiveScan(Unknown Source)
	at burp.g5c.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Traceback (most recent call last):
  File "/home/user/Dragon/Bug_Hunter/SecretFinder-master/BurpSuite-SecretFinder/SecretFinder.py", line 113, in doPassiveScan
    BurpExtender.issuename%(' '.join([x.title() for x in reg[0].split('_')])), 
  File "/home/user/Dragon/Bug_Hunter/SecretFinder-master/BurpSuite-SecretFinder/SecretFinder.py", line 144, in findRegEx
    encoded_resp=binascii.b2a_base64(self._helpers.bytesToString(response))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 4840-4842: ordinal not in range(128)

	at org.python.core.codecs.strict_errors(codecs.java:206)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.python.core.JavaFunc.__call__(Py.java:2895)
	at org.python.core.PyObject.__call__(PyObject.java:433)
	at org.python.core.codecs.encoding_error(codecs.java:1537)
	at org.python.core.codecs.PyUnicode_EncodeIntLimited(codecs.java:1210)
	at org.python.core.codecs.PyUnicode_EncodeASCII(codecs.java:1169)
	at org.python.core.codecs.encode(codecs.java:163)
	at org.python.core.PyString.encode(PyString.java:3995)
	at org.python.core.PyString.encode(PyString.java:3987)
	at org.python.modules.binascii.getByteBuffer(binascii.java:1056)
	at org.python.modules.binascii.b2a_base64(binascii.java:452)
	at sun.reflect.GeneratedMethodAccessor104.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.python.core.PyReflectedFunction.__call__(PyReflectedFunction.java:190)
	at org.python.core.PyReflectedFunction.__call__(PyReflectedFunction.java:208)
	at org.python.core.PyObject.__call__(PyObject.java:461)
	at org.python.core.PyObject.__call__(PyObject.java:465)
	at org.python.pycode._pyx4.findRegEx$8(/home/user/Dragon/Bug_Hunter/SecretFinder-master/BurpSuite-SecretFinder/SecretFinder.py:167)
	at org.python.pycode._pyx4.call_function(/home/user/Dragon/Bug_Hunter/SecretFinder-master/BurpSuite-SecretFinder/SecretFinder.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:173)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:306)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:197)
	at org.python.core.PyFunction.__call__(PyFunction.java:485)
	at org.python.core.PyMethod.__call__(PyMethod.java:187)
	at org.python.pycode._pyx4.doPassiveScan$5(/home/user/Dragon/Bug_Hunter/SecretFinder-master/BurpSuite-SecretFinder/SecretFinder.py:122)
	at org.python.pycode._pyx4.call_function(/home/user/Dragon/Bug_Hunter/SecretFinder-master/BurpSuite-SecretFinder/SecretFinder.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:173)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:306)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:197)
	at org.python.core.PyFunction.__call__(PyFunction.java:485)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:237)
	at org.python.core.PyMethod.__call__(PyMethod.java:228)
	at org.python.core.PyMethod.__call__(PyMethod.java:218)
	at org.python.core.PyMethod.__call__(PyMethod.java:213)
	at org.python.core.PyObject._jcallexc(PyObject.java:3565)
	at org.python.core.PyObject._jcall(PyObject.java:3598)
	at org.python.proxies.__main__$BurpExtender$7.doPassiveScan(Unknown Source)
	at burp.g5c.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by m4ll0k** [comment]
your  jython version?

**Comment by KiDxS** [comment]
@m4ll0k , sorry for pinging you when you are so very busy. 

I'm also having a problem with this in burp v2021, my jython version is 2.7.1. 

May I know the jython version you've used the time this was working for you?

**Comment by thisguy23** [comment]
same issue here

**Comment by umeshgain** [comment]
It worked for me in Burp in the 2023.8 version with jython 2.7.2, but after the upgrade of Burp from 2023.8 it stopped working
