### ISSUE TITLE
Can't run anything after install in Kali Linux

### ISSUE THREAD

**Issue by zabeliqbal** [m4ll0k/SecretFinder#55]
Traceback (most recent call last):
  File "/root/Downloads/secretfinder/SecretFinder.py", line 435, in <module>
    matched = parser_file(file,mode)
  File "/root/Downloads/secretfinder/SecretFinder.py", line 182, in parser_file
    items = getContext(all_matches,content,regex[0])
  File "/root/Downloads/secretfinder/SecretFinder.py", line 158, in getContext
    context = re.findall('%s%s%s'%(rex,m,rex),content,re.IGNORECASE)
  File "/usr/lib/python3.9/re.py", line 241, in findall
    return _compile(pattern, flags).findall(string)
  File "/usr/lib/python3.9/re.py", line 304, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/usr/lib/python3.9/sre_compile.py", line 764, in compile
    p = sre_parse.parse(p, flags)
  File "/usr/lib/python3.9/sre_parse.py", line 962, in parse
    raise source.error("unbalanced parenthesis")
re.error: unbalanced parenthesis at position 21

**Comment by shakato** [comment]
same here, any solution?
