### ISSUE TITLE
help

### ISSUE THREAD

**Issue by sasholy** [m4ll0k/SecretFinder#62]
how fix it

Traceback (most recent call last):
  File "/home/kali/secretfinder/SecretFinder.py", line 435, in <module>
    matched = parser_file(file,mode)
  File "/home/kali/secretfinder/SecretFinder.py", line 182, in parser_file
    items = getContext(all_matches,content,regex[0])
  File "/home/kali/secretfinder/SecretFinder.py", line 158, in getContext
    context = re.findall('%s%s%s'%(rex,m,rex),content,re.IGNORECASE)
  File "/usr/lib/python3.10/re.py", line 240, in findall
    return _compile(pattern, flags).findall(string)
  File "/usr/lib/python3.10/re.py", line 303, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/usr/lib/python3.10/sre_compile.py", line 764, in compile
    p = sre_parse.parse(p, flags)
  File "/usr/lib/python3.10/sre_parse.py", line 950, in parse
    p = _parse_sub(source, state, flags & SRE_FLAG_VERBOSE, 0)
  File "/usr/lib/python3.10/sre_parse.py", line 443, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
  File "/usr/lib/python3.10/sre_parse.py", line 838, in _parse
    raise source.error("missing ), unterminated subpattern",
re.error: missing ), unterminated subpattern at position 15

 thx

**Comment by ITZMEHIMANSHUKING** [comment]
Don't know

**Comment by tester-zero** [comment]
It looks like you're encountering an error with a missing parenthesis in a regex pattern.
